### ISSUE TITLE
pydantic type issue

### ISSUE THREAD

**Issue by justKishore** [ScrapeGraphAI/Scrapegraph-ai#676] opened 2024-09-17 11:04 UTC
I tried running https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/examples/openai/smart_scraper_schema_openai.py

I'm getting the following issue

pydantic_core._pydantic_core.ValidationError: 1 validation error for Generation
text
  Input should be a valid string [type=string_type, input_value=Projects(projects=[Projec...eived maximum grade.')]), input_type=Projects]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
    
 Ps - I'm using pydantic instead of  langchain_core.pydantic_v1

**Comment by LorenzoPaleari** [comment] 2024-09-17 12:00
Hi,
It is a duplicate of #598

It has been fixed in the beta version: 1.20.0-beta1
`pip install scrapegraphai==1.20.0b1`

**Comment by VinciGit00** [comment] 2024-09-17 13:59
Hi, please update to the beta

**Closed by VinciGit00** 2024-09-17 13:59 UTC

**Comment by justKishore** [comment] 2024-09-18 06:46
Fixed :)
